//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsAppNaloga5.FirstWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AvtoVAvtosalonu", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class AvtoVAvtosalonu : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int avtoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int avtosaloniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int avto {
            get {
                return this.avtoField;
            }
            set {
                if ((this.avtoField.Equals(value) != true)) {
                    this.avtoField = value;
                    this.RaisePropertyChanged("avto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int avtosaloni {
            get {
                return this.avtosaloniField;
            }
            set {
                if ((this.avtosaloniField.Equals(value) != true)) {
                    this.avtosaloniField = value;
                    this.RaisePropertyChanged("avtosaloni");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Avtosalon", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Avtosalon : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string krajField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int letoUstanovitveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nazivField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string kraj {
            get {
                return this.krajField;
            }
            set {
                if ((object.ReferenceEquals(this.krajField, value) != true)) {
                    this.krajField = value;
                    this.RaisePropertyChanged("kraj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int letoUstanovitve {
            get {
                return this.letoUstanovitveField;
            }
            set {
                if ((this.letoUstanovitveField.Equals(value) != true)) {
                    this.letoUstanovitveField = value;
                    this.RaisePropertyChanged("letoUstanovitve");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string naziv {
            get {
                return this.nazivField;
            }
            set {
                if ((object.ReferenceEquals(this.nazivField, value) != true)) {
                    this.nazivField = value;
                    this.RaisePropertyChanged("naziv");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Avto", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Avto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string modelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string znamkaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cena {
            get {
                return this.cenaField;
            }
            set {
                if ((this.cenaField.Equals(value) != true)) {
                    this.cenaField = value;
                    this.RaisePropertyChanged("cena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string model {
            get {
                return this.modelField;
            }
            set {
                if ((object.ReferenceEquals(this.modelField, value) != true)) {
                    this.modelField = value;
                    this.RaisePropertyChanged("model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string znamka {
            get {
                return this.znamkaField;
            }
            set {
                if ((object.ReferenceEquals(this.znamkaField, value) != true)) {
                    this.znamkaField = value;
                    this.RaisePropertyChanged("znamka");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UporabniskiRacun", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class UporabniskiRacun : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormsAppNaloga5.FirstWebService.UporabniskiRacun.Admin adminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string gesloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string uporabniskoImeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsFormsAppNaloga5.FirstWebService.UporabniskiRacun.Admin admin {
            get {
                return this.adminField;
            }
            set {
                if ((this.adminField.Equals(value) != true)) {
                    this.adminField = value;
                    this.RaisePropertyChanged("admin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string geslo {
            get {
                return this.gesloField;
            }
            set {
                if ((object.ReferenceEquals(this.gesloField, value) != true)) {
                    this.gesloField = value;
                    this.RaisePropertyChanged("geslo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string uporabniskoIme {
            get {
                return this.uporabniskoImeField;
            }
            set {
                if ((object.ReferenceEquals(this.uporabniskoImeField, value) != true)) {
                    this.uporabniskoImeField = value;
                    this.RaisePropertyChanged("uporabniskoIme");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="UporabniskiRacun.Admin", Namespace="http://schemas.datacontract.org/2004/07/")]
        public enum Admin : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            da = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ne = 1,
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FirstWebService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/IzpisAdmin", ReplyAction="http://tempuri.org/IService/IzpisAdminResponse")]
        WindowsFormsAppNaloga5.FirstWebService.AvtoVAvtosalonu[] IzpisAdmin();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/IzpisAdmin", ReplyAction="http://tempuri.org/IService/IzpisAdminResponse")]
        System.Threading.Tasks.Task<WindowsFormsAppNaloga5.FirstWebService.AvtoVAvtosalonu[]> IzpisAdminAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/najstarejsiAvtosalon", ReplyAction="http://tempuri.org/IService/najstarejsiAvtosalonResponse")]
        WindowsFormsAppNaloga5.FirstWebService.Avtosalon najstarejsiAvtosalon();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/najstarejsiAvtosalon", ReplyAction="http://tempuri.org/IService/najstarejsiAvtosalonResponse")]
        System.Threading.Tasks.Task<WindowsFormsAppNaloga5.FirstWebService.Avtosalon> najstarejsiAvtosalonAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/najvecAvtomobilov", ReplyAction="http://tempuri.org/IService/najvecAvtomobilovResponse")]
        WindowsFormsAppNaloga5.FirstWebService.Avtosalon najvecAvtomobilov();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/najvecAvtomobilov", ReplyAction="http://tempuri.org/IService/najvecAvtomobilovResponse")]
        System.Threading.Tasks.Task<WindowsFormsAppNaloga5.FirstWebService.Avtosalon> najvecAvtomobilovAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PovprecnavrednostAvtov", ReplyAction="http://tempuri.org/IService/PovprecnavrednostAvtovResponse")]
        double PovprecnavrednostAvtov();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PovprecnavrednostAvtov", ReplyAction="http://tempuri.org/IService/PovprecnavrednostAvtovResponse")]
        System.Threading.Tasks.Task<double> PovprecnavrednostAvtovAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Uporabnik", ReplyAction="http://tempuri.org/IService/UporabnikResponse")]
        bool Uporabnik(string Ime, string geslo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Uporabnik", ReplyAction="http://tempuri.org/IService/UporabnikResponse")]
        System.Threading.Tasks.Task<bool> UporabnikAsync(string Ime, string geslo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/VrniAvte", ReplyAction="http://tempuri.org/IService/VrniAvteResponse")]
        WindowsFormsAppNaloga5.FirstWebService.Avto[] VrniAvte();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/VrniAvte", ReplyAction="http://tempuri.org/IService/VrniAvteResponse")]
        System.Threading.Tasks.Task<WindowsFormsAppNaloga5.FirstWebService.Avto[]> VrniAvteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/VrniAvtoSalone", ReplyAction="http://tempuri.org/IService/VrniAvtoSaloneResponse")]
        WindowsFormsAppNaloga5.FirstWebService.Avtosalon[] VrniAvtoSalone();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/VrniAvtoSalone", ReplyAction="http://tempuri.org/IService/VrniAvtoSaloneResponse")]
        System.Threading.Tasks.Task<WindowsFormsAppNaloga5.FirstWebService.Avtosalon[]> VrniAvtoSaloneAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/VrniAvteVSalonu", ReplyAction="http://tempuri.org/IService/VrniAvteVSalonuResponse")]
        WindowsFormsAppNaloga5.FirstWebService.AvtoVAvtosalonu[] VrniAvteVSalonu();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/VrniAvteVSalonu", ReplyAction="http://tempuri.org/IService/VrniAvteVSalonuResponse")]
        System.Threading.Tasks.Task<WindowsFormsAppNaloga5.FirstWebService.AvtoVAvtosalonu[]> VrniAvteVSalonuAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DodajAvto", ReplyAction="http://tempuri.org/IService/DodajAvtoResponse")]
        void DodajAvto(string znamka, string model, int cena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DodajAvto", ReplyAction="http://tempuri.org/IService/DodajAvtoResponse")]
        System.Threading.Tasks.Task DodajAvtoAsync(string znamka, string model, int cena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DodajAvtoSalon", ReplyAction="http://tempuri.org/IService/DodajAvtoSalonResponse")]
        void DodajAvtoSalon(string naziv, string kraj, int LetoUstanovitve);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DodajAvtoSalon", ReplyAction="http://tempuri.org/IService/DodajAvtoSalonResponse")]
        System.Threading.Tasks.Task DodajAvtoSalonAsync(string naziv, string kraj, int LetoUstanovitve);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DodajAvtoVSalon", ReplyAction="http://tempuri.org/IService/DodajAvtoVSalonResponse")]
        void DodajAvtoVSalon(int idAvtosalona, int idavta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DodajAvtoVSalon", ReplyAction="http://tempuri.org/IService/DodajAvtoVSalonResponse")]
        System.Threading.Tasks.Task DodajAvtoVSalonAsync(int idAvtosalona, int idavta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/poosodobiAvto", ReplyAction="http://tempuri.org/IService/poosodobiAvtoResponse")]
        void poosodobiAvto(int a, string znamka, string model, int cena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/poosodobiAvto", ReplyAction="http://tempuri.org/IService/poosodobiAvtoResponse")]
        System.Threading.Tasks.Task poosodobiAvtoAsync(int a, string znamka, string model, int cena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/poosodobiAvtoSalon", ReplyAction="http://tempuri.org/IService/poosodobiAvtoSalonResponse")]
        void poosodobiAvtoSalon(int a, string naziv, string kraj, int leto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/poosodobiAvtoSalon", ReplyAction="http://tempuri.org/IService/poosodobiAvtoSalonResponse")]
        System.Threading.Tasks.Task poosodobiAvtoSalonAsync(int a, string naziv, string kraj, int leto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/posodobiUporabniskiRacun", ReplyAction="http://tempuri.org/IService/posodobiUporabniskiRacunResponse")]
        void posodobiUporabniskiRacun(int id, string Ime, string geslo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/posodobiUporabniskiRacun", ReplyAction="http://tempuri.org/IService/posodobiUporabniskiRacunResponse")]
        System.Threading.Tasks.Task posodobiUporabniskiRacunAsync(int id, string Ime, string geslo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/poosodobiAvtoVSalonu", ReplyAction="http://tempuri.org/IService/poosodobiAvtoVSalonuResponse")]
        void poosodobiAvtoVSalonu(int id, int idavta, int idavtosalona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/poosodobiAvtoVSalonu", ReplyAction="http://tempuri.org/IService/poosodobiAvtoVSalonuResponse")]
        System.Threading.Tasks.Task poosodobiAvtoVSalonuAsync(int id, int idavta, int idavtosalona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/IzbrisiAvto", ReplyAction="http://tempuri.org/IService/IzbrisiAvtoResponse")]
        void IzbrisiAvto(int avtoid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/IzbrisiAvto", ReplyAction="http://tempuri.org/IService/IzbrisiAvtoResponse")]
        System.Threading.Tasks.Task IzbrisiAvtoAsync(int avtoid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/IzbrisiAvtoSalon", ReplyAction="http://tempuri.org/IService/IzbrisiAvtoSalonResponse")]
        void IzbrisiAvtoSalon(int avtoSalonid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/IzbrisiAvtoSalon", ReplyAction="http://tempuri.org/IService/IzbrisiAvtoSalonResponse")]
        System.Threading.Tasks.Task IzbrisiAvtoSalonAsync(int avtoSalonid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DodajAvtoVavtoSalon", ReplyAction="http://tempuri.org/IService/DodajAvtoVavtoSalonResponse")]
        void DodajAvtoVavtoSalon(int avto, int avtosalon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DodajAvtoVavtoSalon", ReplyAction="http://tempuri.org/IService/DodajAvtoVavtoSalonResponse")]
        System.Threading.Tasks.Task DodajAvtoVavtoSalonAsync(int avto, int avtosalon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DodajAvtosalonAvtu", ReplyAction="http://tempuri.org/IService/DodajAvtosalonAvtuResponse")]
        void DodajAvtosalonAvtu(int avtoid, int savtolonid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DodajAvtosalonAvtu", ReplyAction="http://tempuri.org/IService/DodajAvtosalonAvtuResponse")]
        System.Threading.Tasks.Task DodajAvtosalonAvtuAsync(int avtoid, int savtolonid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/OdstraniAvtoVavtosalonu", ReplyAction="http://tempuri.org/IService/OdstraniAvtoVavtosalonuResponse")]
        void OdstraniAvtoVavtosalonu(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/OdstraniAvtoVavtosalonu", ReplyAction="http://tempuri.org/IService/OdstraniAvtoVavtosalonuResponse")]
        System.Threading.Tasks.Task OdstraniAvtoVavtosalonuAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DodajUporabnika", ReplyAction="http://tempuri.org/IService/DodajUporabnikaResponse")]
        void DodajUporabnika(string Ime, string geslo, string admin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DodajUporabnika", ReplyAction="http://tempuri.org/IService/DodajUporabnikaResponse")]
        System.Threading.Tasks.Task DodajUporabnikaAsync(string Ime, string geslo, string admin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/OdstraniUporabnika", ReplyAction="http://tempuri.org/IService/OdstraniUporabnikaResponse")]
        void OdstraniUporabnika(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/OdstraniUporabnika", ReplyAction="http://tempuri.org/IService/OdstraniUporabnikaResponse")]
        System.Threading.Tasks.Task OdstraniUporabnikaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/VrniVseUporabnike", ReplyAction="http://tempuri.org/IService/VrniVseUporabnikeResponse")]
        WindowsFormsAppNaloga5.FirstWebService.UporabniskiRacun[] VrniVseUporabnike();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/VrniVseUporabnike", ReplyAction="http://tempuri.org/IService/VrniVseUporabnikeResponse")]
        System.Threading.Tasks.Task<WindowsFormsAppNaloga5.FirstWebService.UporabniskiRacun[]> VrniVseUporabnikeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/IzbrisiVseAvte", ReplyAction="http://tempuri.org/IService/IzbrisiVseAvteResponse")]
        void IzbrisiVseAvte();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/IzbrisiVseAvte", ReplyAction="http://tempuri.org/IService/IzbrisiVseAvteResponse")]
        System.Threading.Tasks.Task IzbrisiVseAvteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/OdstraniAvtomobilIzsalona", ReplyAction="http://tempuri.org/IService/OdstraniAvtomobilIzsalonaResponse")]
        void OdstraniAvtomobilIzsalona(int avtoid, int avtosalonid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/OdstraniAvtomobilIzsalona", ReplyAction="http://tempuri.org/IService/OdstraniAvtomobilIzsalonaResponse")]
        System.Threading.Tasks.Task OdstraniAvtomobilIzsalonaAsync(int avtoid, int avtosalonid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Odstranilastnistvoavtosalonanadavtom", ReplyAction="http://tempuri.org/IService/OdstranilastnistvoavtosalonanadavtomResponse")]
        void Odstranilastnistvoavtosalonanadavtom(int avtoid, int avtosalonid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Odstranilastnistvoavtosalonanadavtom", ReplyAction="http://tempuri.org/IService/OdstranilastnistvoavtosalonanadavtomResponse")]
        System.Threading.Tasks.Task OdstranilastnistvoavtosalonanadavtomAsync(int avtoid, int avtosalonid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/VrniSaloneAvtov", ReplyAction="http://tempuri.org/IService/VrniSaloneAvtovResponse")]
        void VrniSaloneAvtov();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/VrniSaloneAvtov", ReplyAction="http://tempuri.org/IService/VrniSaloneAvtovResponse")]
        System.Threading.Tasks.Task VrniSaloneAvtovAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : WindowsFormsAppNaloga5.FirstWebService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<WindowsFormsAppNaloga5.FirstWebService.IService>, WindowsFormsAppNaloga5.FirstWebService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WindowsFormsAppNaloga5.FirstWebService.AvtoVAvtosalonu[] IzpisAdmin() {
            return base.Channel.IzpisAdmin();
        }
        
        public System.Threading.Tasks.Task<WindowsFormsAppNaloga5.FirstWebService.AvtoVAvtosalonu[]> IzpisAdminAsync() {
            return base.Channel.IzpisAdminAsync();
        }
        
        public WindowsFormsAppNaloga5.FirstWebService.Avtosalon najstarejsiAvtosalon() {
            return base.Channel.najstarejsiAvtosalon();
        }
        
        public System.Threading.Tasks.Task<WindowsFormsAppNaloga5.FirstWebService.Avtosalon> najstarejsiAvtosalonAsync() {
            return base.Channel.najstarejsiAvtosalonAsync();
        }
        
        public WindowsFormsAppNaloga5.FirstWebService.Avtosalon najvecAvtomobilov() {
            return base.Channel.najvecAvtomobilov();
        }
        
        public System.Threading.Tasks.Task<WindowsFormsAppNaloga5.FirstWebService.Avtosalon> najvecAvtomobilovAsync() {
            return base.Channel.najvecAvtomobilovAsync();
        }
        
        public double PovprecnavrednostAvtov() {
            return base.Channel.PovprecnavrednostAvtov();
        }
        
        public System.Threading.Tasks.Task<double> PovprecnavrednostAvtovAsync() {
            return base.Channel.PovprecnavrednostAvtovAsync();
        }
        
        public bool Uporabnik(string Ime, string geslo) {
            return base.Channel.Uporabnik(Ime, geslo);
        }
        
        public System.Threading.Tasks.Task<bool> UporabnikAsync(string Ime, string geslo) {
            return base.Channel.UporabnikAsync(Ime, geslo);
        }
        
        public WindowsFormsAppNaloga5.FirstWebService.Avto[] VrniAvte() {
            return base.Channel.VrniAvte();
        }
        
        public System.Threading.Tasks.Task<WindowsFormsAppNaloga5.FirstWebService.Avto[]> VrniAvteAsync() {
            return base.Channel.VrniAvteAsync();
        }
        
        public WindowsFormsAppNaloga5.FirstWebService.Avtosalon[] VrniAvtoSalone() {
            return base.Channel.VrniAvtoSalone();
        }
        
        public System.Threading.Tasks.Task<WindowsFormsAppNaloga5.FirstWebService.Avtosalon[]> VrniAvtoSaloneAsync() {
            return base.Channel.VrniAvtoSaloneAsync();
        }
        
        public WindowsFormsAppNaloga5.FirstWebService.AvtoVAvtosalonu[] VrniAvteVSalonu() {
            return base.Channel.VrniAvteVSalonu();
        }
        
        public System.Threading.Tasks.Task<WindowsFormsAppNaloga5.FirstWebService.AvtoVAvtosalonu[]> VrniAvteVSalonuAsync() {
            return base.Channel.VrniAvteVSalonuAsync();
        }
        
        public void DodajAvto(string znamka, string model, int cena) {
            base.Channel.DodajAvto(znamka, model, cena);
        }
        
        public System.Threading.Tasks.Task DodajAvtoAsync(string znamka, string model, int cena) {
            return base.Channel.DodajAvtoAsync(znamka, model, cena);
        }
        
        public void DodajAvtoSalon(string naziv, string kraj, int LetoUstanovitve) {
            base.Channel.DodajAvtoSalon(naziv, kraj, LetoUstanovitve);
        }
        
        public System.Threading.Tasks.Task DodajAvtoSalonAsync(string naziv, string kraj, int LetoUstanovitve) {
            return base.Channel.DodajAvtoSalonAsync(naziv, kraj, LetoUstanovitve);
        }
        
        public void DodajAvtoVSalon(int idAvtosalona, int idavta) {
            base.Channel.DodajAvtoVSalon(idAvtosalona, idavta);
        }
        
        public System.Threading.Tasks.Task DodajAvtoVSalonAsync(int idAvtosalona, int idavta) {
            return base.Channel.DodajAvtoVSalonAsync(idAvtosalona, idavta);
        }
        
        public void poosodobiAvto(int a, string znamka, string model, int cena) {
            base.Channel.poosodobiAvto(a, znamka, model, cena);
        }
        
        public System.Threading.Tasks.Task poosodobiAvtoAsync(int a, string znamka, string model, int cena) {
            return base.Channel.poosodobiAvtoAsync(a, znamka, model, cena);
        }
        
        public void poosodobiAvtoSalon(int a, string naziv, string kraj, int leto) {
            base.Channel.poosodobiAvtoSalon(a, naziv, kraj, leto);
        }
        
        public System.Threading.Tasks.Task poosodobiAvtoSalonAsync(int a, string naziv, string kraj, int leto) {
            return base.Channel.poosodobiAvtoSalonAsync(a, naziv, kraj, leto);
        }
        
        public void posodobiUporabniskiRacun(int id, string Ime, string geslo) {
            base.Channel.posodobiUporabniskiRacun(id, Ime, geslo);
        }
        
        public System.Threading.Tasks.Task posodobiUporabniskiRacunAsync(int id, string Ime, string geslo) {
            return base.Channel.posodobiUporabniskiRacunAsync(id, Ime, geslo);
        }
        
        public void poosodobiAvtoVSalonu(int id, int idavta, int idavtosalona) {
            base.Channel.poosodobiAvtoVSalonu(id, idavta, idavtosalona);
        }
        
        public System.Threading.Tasks.Task poosodobiAvtoVSalonuAsync(int id, int idavta, int idavtosalona) {
            return base.Channel.poosodobiAvtoVSalonuAsync(id, idavta, idavtosalona);
        }
        
        public void IzbrisiAvto(int avtoid) {
            base.Channel.IzbrisiAvto(avtoid);
        }
        
        public System.Threading.Tasks.Task IzbrisiAvtoAsync(int avtoid) {
            return base.Channel.IzbrisiAvtoAsync(avtoid);
        }
        
        public void IzbrisiAvtoSalon(int avtoSalonid) {
            base.Channel.IzbrisiAvtoSalon(avtoSalonid);
        }
        
        public System.Threading.Tasks.Task IzbrisiAvtoSalonAsync(int avtoSalonid) {
            return base.Channel.IzbrisiAvtoSalonAsync(avtoSalonid);
        }
        
        public void DodajAvtoVavtoSalon(int avto, int avtosalon) {
            base.Channel.DodajAvtoVavtoSalon(avto, avtosalon);
        }
        
        public System.Threading.Tasks.Task DodajAvtoVavtoSalonAsync(int avto, int avtosalon) {
            return base.Channel.DodajAvtoVavtoSalonAsync(avto, avtosalon);
        }
        
        public void DodajAvtosalonAvtu(int avtoid, int savtolonid) {
            base.Channel.DodajAvtosalonAvtu(avtoid, savtolonid);
        }
        
        public System.Threading.Tasks.Task DodajAvtosalonAvtuAsync(int avtoid, int savtolonid) {
            return base.Channel.DodajAvtosalonAvtuAsync(avtoid, savtolonid);
        }
        
        public void OdstraniAvtoVavtosalonu(int ID) {
            base.Channel.OdstraniAvtoVavtosalonu(ID);
        }
        
        public System.Threading.Tasks.Task OdstraniAvtoVavtosalonuAsync(int ID) {
            return base.Channel.OdstraniAvtoVavtosalonuAsync(ID);
        }
        
        public void DodajUporabnika(string Ime, string geslo, string admin) {
            base.Channel.DodajUporabnika(Ime, geslo, admin);
        }
        
        public System.Threading.Tasks.Task DodajUporabnikaAsync(string Ime, string geslo, string admin) {
            return base.Channel.DodajUporabnikaAsync(Ime, geslo, admin);
        }
        
        public void OdstraniUporabnika(int id) {
            base.Channel.OdstraniUporabnika(id);
        }
        
        public System.Threading.Tasks.Task OdstraniUporabnikaAsync(int id) {
            return base.Channel.OdstraniUporabnikaAsync(id);
        }
        
        public WindowsFormsAppNaloga5.FirstWebService.UporabniskiRacun[] VrniVseUporabnike() {
            return base.Channel.VrniVseUporabnike();
        }
        
        public System.Threading.Tasks.Task<WindowsFormsAppNaloga5.FirstWebService.UporabniskiRacun[]> VrniVseUporabnikeAsync() {
            return base.Channel.VrniVseUporabnikeAsync();
        }
        
        public void IzbrisiVseAvte() {
            base.Channel.IzbrisiVseAvte();
        }
        
        public System.Threading.Tasks.Task IzbrisiVseAvteAsync() {
            return base.Channel.IzbrisiVseAvteAsync();
        }
        
        public void OdstraniAvtomobilIzsalona(int avtoid, int avtosalonid) {
            base.Channel.OdstraniAvtomobilIzsalona(avtoid, avtosalonid);
        }
        
        public System.Threading.Tasks.Task OdstraniAvtomobilIzsalonaAsync(int avtoid, int avtosalonid) {
            return base.Channel.OdstraniAvtomobilIzsalonaAsync(avtoid, avtosalonid);
        }
        
        public void Odstranilastnistvoavtosalonanadavtom(int avtoid, int avtosalonid) {
            base.Channel.Odstranilastnistvoavtosalonanadavtom(avtoid, avtosalonid);
        }
        
        public System.Threading.Tasks.Task OdstranilastnistvoavtosalonanadavtomAsync(int avtoid, int avtosalonid) {
            return base.Channel.OdstranilastnistvoavtosalonanadavtomAsync(avtoid, avtosalonid);
        }
        
        public void VrniSaloneAvtov() {
            base.Channel.VrniSaloneAvtov();
        }
        
        public System.Threading.Tasks.Task VrniSaloneAvtovAsync() {
            return base.Channel.VrniSaloneAvtovAsync();
        }
    }
}
